name: Trace
description: Cryptocurrency portfolio and market explorer.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.1
  path_provider: ^0.4.0
  flutter_circular_chart: ^0.1.0
  url_launcher: ^3.0.3
  http: ^0.12.0
  package_info: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/